package:
  name: "besca"
  version: "2.1"

source:
  git_url: https://github.roche.com/BEDA/besca.git
  git_tag: conda

requirements:
  build:
    - setuptools
    - python
  run:
    - scipy
    - flask-restful
    - dominate
    - requests
    - numpy
    - scanpy
    - plotly
    - anndata
    - seaborn
    - mygene
    - pandas
    - matplotlib
    - bbknn
    - ipython
    - nbclean
    - scikit_learn
    - python-igraph
    - leidenalg
    - scanorama

test:
  imports:
    - besca

about:
  license: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
