name: besca_2.2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=2.17
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - chardet=3.0.4
  - cryptography=3.0
  - dbus=1.13.6
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fuzzywuzzy=0.17.0
  - gettext=0.19.8.1
  - glib=2.65.0
  - gmp=6.2.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - html5lib=1.1
  - icu=64.2
  - igraph=0.8.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipython_genutils=0.2.0
  - jpeg=9d
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.1
  - louvain=0.6.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - ncurses=6.2
  - nose=1.3.7
  - nspr=4.27
  - nss=3.47
  - numpy=1.19.1
  - openblas=0.3.10
  - openssl=1.1.1g
  - pandoc=2.10.1
  - pcre=8.44
  - pickleshare=0.7.5
  - pip=20.2.1
  - pixman=0.38.0
  - prompt_toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycairo=1.19.1
  - pyopenssl=19.1.0
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.6.11
  - python-igraph=0.8.2
  - python_abi=3.6
  - qt=5.12.5
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=49.2.0
  - sqlite=3.32.3
  - texttable=1.6.2
  - tk=8.6.10
  - webencodings=0.5.1
  - wheel=0.34.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - alembic==1.0.8
    - aniso8601==8.0.0
    - anndata==0.7.4
    - annoy==1.15.1
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.6.0
    - backcall==0.1.0
    - bbknn==1.3.12
    - biothings-client==0.2.0
    - bleach==3.1.0
    - cffi==1.12.2
    - click==7.0
    - cloudpickle==0.8.0
    - cycler==0.10.0
    - cython==0.29.6
    - dask==1.1.3
    - decorator==4.3.2
    - defusedxml==0.5.0
    - distributed==1.18.0
    - docutils==0.14
    - dominate==2.5.1
    - fbpca==1.0
    - flask==1.1.2
    - flask-restful==0.3.8
    - geosketch==1.1
    - get-version==2.1
    - h5py==2.10.0
    - heapdict==1.0.0
    - idna==2.8
    - imagesize==1.1.0
    - intervaltree==2.1.0
    - ipykernel==5.1.0
    - ipython==6.2.1
    - ipywidgets==7.4.2
    - itsdangerous==1.1.0
    - jedi==0.13.3
    - jinja2==2.11.2
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - legacy-api-wrap==1.2
    - leidenalg==0.8.1
    - llvmlite==0.33.0
    - loompy==3.0.6
    - mako==1.0.7
    - matplotlib==3.3.0
    - mnnpy==0.1.9.5
    - more-itertools==6.0.0
    - msgpack-python==0.5.6
    - multicoretsne==0.1
    - mygene==3.1.0
    - natsort==6.0.0
    - nbclean==0.3.2
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - nbgrader==0.5.5
    - nbsphinx==0.4.2
    - networkx==2.2
    - notebook==5.7.5
    - numba==0.50.1
    - numexpr==2.6.9
    - numpy-groupies==0+unknown
    - packaging==19.0
    - pandas==1.1.0
    - pandocfilters==1.4.2
    - parso==0.3.4
    - patsy==0.5.1
    - pexpect==4.6.0
    - pillow==7.2.0
    - plotly==3.7.1
    - pluggy==0.9.0
    - prometheus-client==0.6.0
    - prompt-toolkit==1.0.15
    - psutil==5.5.1
    - py==1.8.0
    - pycparser==2.19
    - pygments==2.3.1
    - pymongo==3.6.1
    - pyparsing==2.3.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyrsistent==0.14.11
    - pytest==4.3.0
    - python-dateutil==2.8.0
    - python-editor==1.0.4
    - python-levenshtein==0.12.0
    - pytz==2018.9
    - pyyaml==3.13
    - pyzmq==18.0.0
    - qtconsole==4.4.3
    - requests==2.21.0
    - retrying==1.3.3
    - rpy2==3.0.1
    - scanorama==1.6
    - scanpy==1.5.1
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - scvelo==0.2.2
    - seaborn==0.9.0
    - setuptools-scm==4.1.2
    - simplegeneric==0.8.1
    - sinfo==0.3.1
    - six==1.12.0
    - snowballstemmer==1.2.1
    - sortedcontainers==2.1.0
    - sphinx==1.8.4
    - sphinx-autodoc-annotation==1.0.post1
    - sphinx-automodapi==0.10
    - sphinx-gallery==0.7.0
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-websupport==1.1.0
    - sqlalchemy==1.3.0
    - statsmodels==0.11.1
    - stdlib-list==0.7.0
    - tables==3.4.4
    - tblib==1.3.2
    - terminado==0.8.1
    - testpath==0.4.2
    - threadpoolctl==2.1.0
    - toolz==0.9.0
    - tornado==6.0.1
    - tqdm==4.31.1
    - traitlets==4.3.2
    - umap-learn==0.4.6
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - werkzeug==1.0.1
    - widgetsnbextension==3.4.2
    - zict==0.1.2

