name: besca_2
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - openssl=1.1.1h
  - sphinx_rtd_theme=0.4.3
  - python-levenshtein=0.12.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alembic=1.4.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - brotlipy=0.7.0
  - cffi=1.14.3
  - chardet=3.0.4
  - cryptography=3.1.1
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.3
  - fuzzywuzzy=0.17.0
  - gettext=0.19.8.1
  - glib=2.66.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=67.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.1
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libllvm10=10.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mako=1.1.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mysql-common=8.0.21
  - mysql-libs=8.0.21
  - nbclean=0.3.2
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nbgrader=0.6.1
  - nbsphinx=0.7.1
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - nose=1.3.7
  - notebook=6.1.4
  - nspr=4.29
  - nss=3.58
  - numpy=1.19.2
  - olefile=0.46
  - packaging=20.4
  - pandoc=2.11.0.2
  - pandocfilters=1.4.2
  - parso=0.7.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=19.0.2
  - qt=5.12.9
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sphinx=3.2.1
  - sphinx-automodapi=0.13
  - sphinx-gallery=0.8.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.5
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - aniso8601==8.0.0
    - anndata==0.7.4
    - annoy==1.17.0
    - appdirs==1.4.4
    - bbknn==1.3.12
    - biothings-client==0.2.3
    - click==7.1.2
    - distlib==0.3.1
    - dominate==2.5.2
    - fbpca==1.0
    - flask==1.1.2
    - flask-restful==0.3.8
    - geosketch==1.1
    - get-version==2.1
    - h5py==2.10.0
    - intervaltree==2.1.0
    - itsdangerous==1.1.0
    - joblib==0.17.0
    - legacy-api-wrap==1.2
    - leidenalg==0.8.2
    - llvmlite==0.34.0
    - loompy==3.0.6
    - matplotlib==3.3.2
    - mygene==3.1.0
    - natsort==7.0.1
    - networkx==2.5
    - numba==0.51.2
    - numexpr==2.7.1
    - numpy-groupies==0.9.13
    - pandas==1.1.3
    - patsy==0.5.1
    - pipenv==2020.8.13
    - plotly==4.11.0
    - pydot==1.4.1
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - python-igraph==0.8.3
    - retrying==1.3.3
    - scanorama==1.6
    - scanpy==1.6.0
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - scvelo==0.2.2
    - seaborn==0.11.0
    - setuptools-scm==4.1.2
    - sinfo==0.3.1
    - sortedcontainers==2.2.2
    - statsmodels==0.12.0
    - stdlib-list==0.7.0
    - tables==3.6.1
    - texttable==1.6.3
    - threadpoolctl==2.1.0
    - umap-learn==0.4.6
    - virtualenv==20.0.35
    - virtualenv-clone==0.5.4
    - werkzeug==1.0.1

