name: besca_test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - ld_impl_linux-64=2.35
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.7.8
  - python_abi=3.7
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.4.3
    - aniso8601==8.0.0
    - anndata==0.7.4
    - annoy==1.17.0
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - bbknn==1.3.12
    - biothings-client==0.2.3
    - bleach==3.2.1
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - cycler==0.10.0
    - cython==0.29.21
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distlib==0.3.1
    - dominate==2.5.2
    - entrypoints==0.3
    - fbpca==1.0
    - filelock==3.0.12
    - flask==1.1.2
    - flask-restful==0.3.8
    - fuzzywuzzy==0.18.0
    - geosketch==1.1
    - get-version==2.1
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.0.0
    - intervaltree==2.1.0
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.17.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.2.0
    - legacy-api-wrap==1.2
    - leidenalg==0.8.2
    - llvmlite==0.34.0
    - loompy==3.0.6
    - mako==1.1.3
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - mygene==3.1.0
    - natsort==7.0.1
    - nbclean==0.3.2
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nbgrader==0.6.1
    - nest-asyncio==1.4.1
    - networkx==2.5
    - nose==1.3.7
    - notebook==6.1.4
    - numba==0.51.2
    - numexpr==2.7.1
    - numpy==1.19.2
    - numpy-groupies==0.9.13
    - packaging==20.4
    - pandas==1.1.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.0
    - pipenv==2020.8.13
    - plotly==4.11.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pydot==1.4.1
    - pygments==2.7.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - python-igraph==0.8.3
    - pytz==2020.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - requests==2.24.0
    - retrying==1.3.3
    - scanorama==1.6
    - scanpy==1.6.0
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - scvelo==0.2.2
    - seaborn==0.11.0
    - send2trash==1.5.0
    - setuptools-scm==4.1.2
    - sinfo==0.3.1
    - six==1.15.0
    - sortedcontainers==2.2.2
    - sqlalchemy==1.3.20
    - statsmodels==0.11.1
    - stdlib-list==0.7.0
    - tables==3.6.1
    - terminado==0.9.1
    - testpath==0.4.4
    - texttable==1.6.3
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - tqdm==4.50.2
    - traitlets==5.0.5
    - umap-learn==0.4.6
    - urllib3==1.25.11
    - virtualenv==20.0.35
    - virtualenv-clone==0.5.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - zipp==3.3.1

