name: Build Sphinx Documentation
on:
  workflow_dispatch:

jobs:
  cached-job:
    name: Cached (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Check out the repo and use mamba
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: besca_documentation
            use-mamba: true
      - name: Cache conda packages
        id: cache-conda
        uses: actions/cache@v3
        env:
          cache-name: cache-conda-packages
        with:
          path: ~/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/docs/environment.lock.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/docs/environment.lock.yml') }}
         
      - name: Get Date
        id: get-date
        run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
        shell: bash

      - name: Cache conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('**/docs/environment.lock.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run: mamba env update -n besca_documentation -f docs/environment.lock.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run Sphinx
        run: |
          mamba init
          source ~/.bashrc
          mamba activate besca_documentation
          cd docs
          make html
