name: Build Sphinx Documentation
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  cached-job:
    name: Cached (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v3
               
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version

         
      # - name: Get Date
      #   id: get-date
      #   run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
      #   shell: bash

      # - name: Cache conda env
      #   uses: actions/cache@v3.0.8
      #   with:
      #     path: ${{ env.CONDA }}/envs
      #     key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('**/docs/environments_no_builds.lock.yml') }}-${{ env.CACHE_NUMBER }}
      #   env:
      #     # Increase this value to reset cache if etc/example-environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   id: cache

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        uses: docker://pandoc/core:2.9
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      # - name: Update environment
      #   run: |
      #     conda env update -n besca_create_docu -f docs/environments_no_builds.lock.yml
      #   if: steps.cache.outputs.cache-hit != 'true'

      - name: Poetry install
        run: poetry install

      - name: setup pandoc, needed for nbsphinx
        uses: docker://pandoc/core:2.9

      - name: Run Sphinx
        run: |
          poetry shell
          cd docs
          make html
