
name: Run doctests

on:
  push:
    branches: [ doctests ]
  pull_request:
    branches: [ doctests ]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
          with:
            image: aschmelyun/cleaver:latest
            run: echo "Hello test"
#using: 'docker'
 #   image: 'docker://ghcr.io/${{ github.repository }}:latest'